// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotMappedAttributeListObject.Model;

#nullable disable

namespace NotMappedAttributeListObject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240619013714_migration_name")]
    partial class migration_name
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NotMappedAttributeListObject.Model.FArticle", b =>
                {
                    b.Property<int>("CbMarq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CbMarq"));

                    b.Property<string>("ArRef")
                        .IsRequired()
                        .HasMaxLength(19)
                        .IsUnicode(false)
                        .HasColumnType("varchar(19)")
                        .HasColumnName("AR_Ref");

                    b.HasKey("CbMarq")
                        .HasName("PK_CBMARQ_F_ARTICLE");

                    b.HasIndex(new[] { "ArRef" }, "UKA_F_ARTICLE_AR_Ref")
                        .IsUnique();

                    b.ToTable("FArticles");
                });
#pragma warning restore 612, 618
        }
    }
}
